#!/usr/bin/env python
#
# From the list of files on the command line, return the epoch time
# (as an integer) of the most recently-modified file.

from __future__ import print_function

import os
import sys

newest = None

for arg in sys.argv[1:]:
   mtime = os.stat(arg).st_mtime
   if newest is None or mtime > newest:
       newest = mtime

if newest is None:
    print("ERROR: No files provided", file=sys.stderr)
    sys.exit(1)

print(int(newest))
sys.exit(0)
